NixOS-Users-Against-MIC-Sponsorship/NixOS-Users-Against-MIC-Sponsorship.github.io

signatures/ireneknapp.txt

IreneKnapp

---

src/index.md

Diff should be self-explanatory :)

letter: fix typo / english language mistake

---

signatures/cgranade

Add signature for cgranade

---

signatures/BlueRaccoonTech

- Named afted my GitHub handle (`@BlueRaccoonTech`)
- The commit message contains only my GitHub handle (`BlueRaccoonTech`)
```txt
```

BlueRaccoonTech

---

signatures/emilytrau

Add emilytrau

---

signatures/jakehamilton.txt

jakehamilton

---

signatures/lillian-violet.txt

signature: Lillian-Violet

---

signatures/FedericoSchonborn.txt

FedericoSchonborn

---

signatures/cillianderoiste.txt

cillianderoiste

---

signatures/surfaceflinger.txt

add surfaceflinger

---

signatures/norpol.txt

Thank you all for signing and the initiative.
---
```txt
```

Add norpol

---

signatures/merspieler

- Named afted my GitHub handle (`@merspieler`)
- The commit message contains only my GitHub handle (`merspieler`)

merspieler

---

signatures/hertog.txt

- Named afted my GitHub handle (`@Hertog-lab`)

Signature Hertog

---

signatures/ixhbinphoenix.txt

- Named afted my GitHub handle (`@ixhbinphoenix`)

ixhbinphoenix

---

signatures/pinkcreeper100.txt

pinkcreeper100

---

signatures/spacekookie.txt

spacekookie

---

signatures/schrottkatze.txt

sign as schrottkatze

---

signatures/mangoiv.txt

Add signature mangoiv

---

signatures/asymmetric

asymmetric

---

signatures/freyacodes

Add Freya Arbjerg

---

signatures/yayayayaka

yayayayaka

---

signatures/sleepynix.txt

add sleepynix

---

signatures/JohnnyJayJay

- Named afted my GitHub handle (`@JohnnyJayJay`)
- The commit message contains only my GitHub handle (`JohnnyJayJay`)

JohnnyJayJay

---

signatures/tennox

signed by @tennox

---

signatures/ckie

sign as ckiee

---

signatures/rossabaker

rossabaker

---

signatures/DeeUnderscore.txt

DeeUnderscore

---

signatures/stillinbeta.txt

-  [x] Named afted my GitHub handle (`@githubHandle`)
-  [x] Containing the line of text to show as a signature
```txt
```

stillinbeta

---

signatures/soupglasses.txt

soupglasses

---

signatures/@viscountexx

- Named afted my GitHub handle (`@viscountexx`)
- The commit message contains only my GitHub handle (`viscountexx`)

viscountexx

---

signatures/emilylange
signatures/networkException

emilylange

---

signatures/shanesveller

Sign by Shane Sveller

---

signatures/googleson78

googleson78

---

signatures/Infinidoge.txt

I am adding myself as a signatory, and I have followed the described format. The commit has been signed by my SSH key for good measure.

Signature by Infinidoge

---

signatures/lilyinstarlight

lilyinstarlight

---

signatures/@takouhai

- Named afted my GitHub handle (`@takouhai`)
- The commit message contains only my GitHub handle (`takouhai`)

Adding @takouhai

---

signatures/@kescherCode

- Containing the line of text to show as a signature (Name + domain)

kescherCode

---

signatures/Eisfunke

add @Eisfunke

---

signatures/@LordGrimmauld

LordGrimmauld

---

signatures/Scrumplex.txt

Add Scrumplex

---

signatures/@jalil-salame

Add @jalil-salame

---

signatures/@artemislena

artemislena

---

signatures/@AgathaSorceress

AgathaSorceress

---

signatures/@GabTheBab

Add @GabTheBab

---

signatures/@deingithub

deingithub

---

signatures/pauliesnug

pauliesnug

---

signatures/@KaiserCalm

- Named afted my GitHub handle (`@KaiserCalm`)
- The commit message contains only my GitHub handle (`KaiserCalm`)
```txt
Deividas Paukštė (@KaiserCalm)
```

KaiserCalm

---

signatures/williamvds

williamvds

---

signatures/pamplemousse

pamplemousse

---

signatures/vaibhavsagar

- Named afted my GitHub handle (`@vaibhavsagar`)
- The commit message contains only my GitHub handle (`vaibhavsagar`)
```txt
```

vaibhavsagar

---

signatures/AxelSilverdew

- Named afted my GitHub handle (`@AxelSilverdew`)
- The commit message contains only my GitHub handle (`AxelSilverdew`)

AxelSilverdew

---

signatures/firestack

Add Myself

---

signatures/michaelshmitty

michaelshmitty

---

signatures/liketechnik

liketechnik

---

support/website/default.nix

Add's a simple count, for anyone following along!

add a simple count

---

signatures/yvan-sraka

```txt
Yvan Sraka (@yvan-sraka)
```

yvan-sraka

---

signatures/dunkelstern

- Named afted my GitHub handle (`@dunkelstern`)
- The commit message contains only my GitHub handle (`dunkelstern`)
```txt
```

dunkelstern

---

signatures/erictapen

add @erictapen

---

signatures/kira-bruneau

kira-bruneau

---

signatures/eripa

eripa signature

---

signatures/frontsideair

- Named after my GitHub handle (`@frontsideair`)
- The commit message contains only my GitHub handle (`frontsideair`)

Add frontsideair

---

signatures/okkdev

sign okkdev

---

signatures/naidneelttil

naidneelttil

---

signatures/waltermoreira.txt

Add waltermoreira

---

signatures/Gaelan

Add Gaelan

---

signatures/Alper-Celik

Alper Çelik

---

signatures/davidak

Add davidak

---

signatures/baerlkr

added BaerLKR

---

signatures/Anomalocaridid

Anomalocaridid

---

signatures/MostAwesomeDude

Sign the letter

---

signatures/oliviacrain

oliviacrain

---

signatures/CutestNekoAqua

CutestNekoAqua

---

signatures/crmsnbleyd

- Named after my GitHub handle (`@crmsnbleyd`)
- The commit message contains only my GitHub handle (`crmsnbleyd`)

crmsnbleyd

---

signatures/endocrimes

endocrimes

---

signatures/Benjamin-L

- Named after my GitHub handle (`@Benjamin-L`)
- The commit message contains only my GitHub handle (`Benjamin-L`)

Benjamin-L

---

signatures/JohnRTitor

- Named after my GitHub handle (`@JohnRTitor`)
- The commit message contains only my GitHub handle (`JohnRTitor`)

JohnRTitor: Add signature

---

signatures/vikanezrimaya

@vikanezrimaya

---

signatures/halian

/s/ halian

---

signatures/DerRockWolf

DerRockWolf

---

signatures/turkeysanwich

turkeysanwich

---

signatures/misterio77

misterio77

---

signatures/tomodachi94

tomodachi94
